### ISSUE TITLE
Derived quantities should error more gracefully when abundance is None

### ISSUE THREAD

**Issue by nsshirman** [wtbarnes/fiasco#89]
Received this error when trying to calculate the contribution function for Cr 9 for the 211 channel. Original used 'sun_coronal_1992_feldman' as the abundance file, also tried 'grevesse_photospheric_1998' - neither worked. 

```
Traceback (most recent call last):

  File "<ipython-input-475-5f00bd24d0c3>", line 1, in <module>
    K_nT, K_T, KT_dict, ch, response, temperature = temp_resp(211, 'chromium 9')

  File "/Users/shirman/Desktop/DEM.py", line 46, in temp_resp
    g = ion_name.contribution_function(density)

  File "/Users/shirman/fiasco/fiasco/util/decorators.py", line 22, in func_wrapper
    return func(*args, **kwargs)

  File "/Users/shirman/anaconda3/lib/python3.7/site-packages/astropy/units/decorators.py", line 234, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)

  File "/Users/shirman/fiasco/fiasco/ion.py", line 384, in contribution_function
    term = np.outer(self.ioneq, 1./density) * self.abundance * 0.83

  File "/Users/shirman/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 947, in __mul__
    return super().__mul__(other)

  File "/Users/shirman/anaconda3/lib/python3.7/site-packages/astropy/units/quantity.py", line 481, in __array_ufunc__
    result = super().__array_ufunc__(function, method, *arrays, **kwargs)

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```

**Comment by wtbarnes** [comment]
Thanks for submitting this Nina!

I think the fundamental issue here is that when an abundance is not available from a given dataset for a specific element, the calculation for the derived quantities does not really know how to handle the resulting `None` values that pop out of the `Ion.abundance` properties. 

One easy solution would be to just require the `abundance` property on these derived quantities. In fiasco, this can be done with the `needs_dataset` decorator. This would then return `None` for these derived quantities.

This really touches on the larger issue of how to deal with missing datasets and how this missing data should be propagated through these calculations. I'm not sure what a solution to this looks like currently.
